"""del

Revision ID: a842c86629a0
Revises: 2a6ed9064d91
Create Date: 2020-03-13 20:48:30.927277

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a842c86629a0'
down_revision = '2a6ed9064d91'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_folder_folder_id', table_name='folder')
    op.drop_table('folder')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('folder',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('folder_id', sa.INTEGER(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_folder_folder_id', 'folder', ['folder_id'], unique=1)
    # ### end Alembic commands ###
